### ISSUE TITLE
no request handler registered for py_nvim_gpt:command:GPTOpen

### ISSUE THREAD

**Issue by six0h** [archibate/nvim-gpt#2]
Hi there, just having an issue after installation

```
Error detected while processing function remote#define#request:
line    2:
Error invoking '/home/code/.local/share/nvim/site/pack/packer/start/nvim-gpt/rplugin/python3/py_nvim_gpt:command:GPTOpen' on channel
3 (python3-rplugin-host):
no request handler registered for "/home/code/.local/share/nvim/site/pack/packer/start/nvim-gpt/rplugin/python3/py_nvim_gpt:command:G
PTOpen"
Press ENTER or type command to continue
```

I've installed with Packer including the minimal setup code provided in the example. I have python3 installed, I've tried the UpdateRemotePlugins command. I have the neovim package installed through pip.

Your help will be greatly appreciated, thanks!

**Comment by archibate** [comment]
Thank for your report, the plugin seems failed to work when having some setup keys empty... fixed this in latest commit!
